### ISSUE TITLE
AssemblyScript Public Meeting #20 - September 9th, 2020

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/working-group#45]
# Date and Time

This public meeting will take place: September 9th, 2020, 18:00 UTC (11:00 AM US PDT, UTC -8)

# General Agenda

* Agenda Items from comments left on this Github issue
* Additional in-meeting comments / discussion
* [If time allows] Recap of [WebAssembly CG meeting](https://github.com/WebAssembly/meetings) if anyone attended

Feel free to comment on this issue if you have any agenda items you would like to bring up. 
Meeting Notes will be placed on this issue for those who cannot make the meeting.

# Meeting Information

We will use Google Meet for our meetings. Our meeting room is: https://meet.google.com/ofw-zkpi-aek . You can also [add the event to your Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=cjU0ajZtY2MwajY2NTMxOHVwNzlvb2VnOGlfMjAyMDA1MDZUMTgwMDAwWiBhYXJvbkBhYXJvbnRoZWRldi5jb20&tmsrc=aaron%40aaronthedev.com)

Anyone who is contributing to the AssemblyScript project, building something with AssemblyScript, interested in the Assembly project or WebAssembly in general, is welcome to join! 😄

Notes will be taken by the host, and posted after the meeting. Notes are free to be edited through comments on the meeting notes at a later time.

**Comment by DuncanUszkay1** [comment]
I'd like to talk about the Closures plan I put forward: https://github.com/AssemblyScript/assemblyscript/issues/798#issuecomment-688542612

**Comment by torch2424** [comment]
@battlelinegames mentioned to me they want to show a AS game demo they are working on! 

https://embed.com/wasm/asteroid.html

(They mentioned it still needs sound :smile: )

**Comment by torch2424** [comment]
We are now in the AS discord. In order to make things less confusing, will be using the discord going forward :smile:

**Comment by torch2424** [comment]
* @battlelinegames ‘s game demo 
   * https://embed.com/wasm/asteroid.html 
   * Function overloading
      * @willemneal : Not yet supported, can’t have the same function name with different signatures
         * Could use generics, but you’ll have to switch on the instance
   * OOP - Inheritance
      * @willemneal : Subclassing should be working
   * @battlelinegames : WebGl Lib - Just made sure the stuff works :) 
      * Can just write tutorials on what I have now, and keep writing the webgl as I go?
      * Or just keep writing more webgl stuff before tutorials
   * Sound effects
      * @torch2424 : I can help make sound effects in sfxr / bfxr
      * @battlelinegames : I just need an mp3 or ogg file :) 
* @DuncanUszkay1 Closures
   * New plan for closures: https://github.com/AssemblyScript/assemblyscript/issues/798#issuecomment-688542612 
   * @dcodeIO : May not necessarily need a class, maybe just an internal representation and should be good
   * @dcodeIO : Env locals can get some binaryen optimizations
   * https://github.com/AssemblyScript/assemblyscript/issues/798#issuecomment-689739958 
* @torch2424 Talks
   * Code Remote talk
   * WebAssembly Live Talk
   * Code Mesh Talk
* @jayphelps : AnyRef Updates
   * @dcodeIO : Once are some GC stuff is in, Anyref stuff can be added :) 
* @willemneal : Talks
   * Giving a talk about Wasm EVM, but will give some AS shoutouts
* @willemneal : Fixed a bug in asbuild
   * Should we move to AS org?
   * @dcodeIO : Sure! 
      * I would just like some dependencies slimmed. But moving now or later is fine :)
* @battlelinegames : Can we make a gamedev 
   * @torch2424 : Done!

**Comment by torch2424** [comment]
Closing this in favor of: https://github.com/AssemblyScript/working-group/issues/46
