### ISSUE TITLE
AssemblyScript Public Meeting #31 - February 24th, 2021

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/working-group#56]
# Date and Time

This public meeting will take place: **February 24th, 2021, 18:00 UTC (10:00 AM US PST, UTC -8)**

# General Agenda

* Agenda Items from comments left on this Github issue
* Additional in-meeting comments / discussion
* [If time allows] Recap of [WebAssembly CG meeting](https://github.com/WebAssembly/meetings) if anyone attended

Feel free to comment on this issue if you have any agenda items you would like to bring up. 
Meeting Notes will be placed on this issue for those who cannot make the meeting.

# Meeting Information

We will use the AssemblyScript discord for meetings: https://discord.gg/vSBbJ5T . We will meet in the "meeting" voice channel :+1: 

Anyone who is contributing to the AssemblyScript project, building something with AssemblyScript, interested in the Assembly project or WebAssembly in general, is welcome to join! 😄

Notes will be taken by the host, and posted after the meeting. Notes are free to be edited through comments on the meeting notes at a later time.

**Comment by torch2424** [comment]
I'd like to chat about: https://github.com/AssemblyScript/assemblyscript/pull/357#issuecomment-776360012

I want to pull this Date implementation into it's own library. But, would anyone be opposed? I think there's a question here about stand-in 3p libraries vs. stdlib. :thinking:

**Comment by dcodeIO** [comment]
I am totally for pulling it into it's own library to make it usable today. The community may then improve it in collaboration, and we may even decide to pull it upstream eventually :)

**Comment by torch2424** [comment]
@dcodeIO If you're also in support, perhaps we can pull it into an `AssemblyScript/as-date` ? And then leave a notice on the top, it's an interim library while we polish one for the stdlib? Or do you think that'd be too confusing? (I'd also be happy to put it under my github, either works :smile: )

**Comment by dcodeIO** [comment]
Sure, why not! Something like "staging package for Date support in AS" or so :)

**Comment by dcodeIO** [comment]
We may want to make sure however that there is no copyright problem before pulling it into the org. Iirc, the implementation is based on Java's stdlib, so need to check the license there.

**Comment by torch2424** [comment]
> Sure, why not! Something like "staging package for Date support in AS" or so :)

Awesome! I think I have access to do that on the org. :smile: I'll probably start that sometime later this week, or sometime next week (Currently finishing up a ton of PRs on my Fastly AS work :smile: )

> We may want to make sure however that there is no copyright problem before pulling it into the org. Iirc, the implementation is based on Java's stdlib, so need to check the license there.

Very good point, I'll take a look at that :smile:

**Comment by torch2424** [comment]
Also, if Willem is there, we could probably chat about making the `assemblyscript-json`, JSON object in the package global? :smile:

**Comment by torch2424** [comment]
## Meeting Notes

* @torch2424 : Date implementation
   * @willemneal : Someone from stoic might also be working on it
* @torch2424 : assemblyscript-json making JSON global
   * @willemneal : I tried everything I could think of, so our options are
      * Allow global on an import
      * Go back to using a namespace
   * @dcodeIO : Maybe just extend it?
      * @willemneal : That wont allow the two separate types to resolve (the original and extended)
   * @torch2424 : we can make multiple entry points?
      * @dcodeIO : should work if not we can fix it in --lib
      * @willemneal : I’ll try that out!
   * @willemneal : (Tried it locally, it works!) :)
* @torch2424 : been working on stuff
   * Talk on Saturday
      * Will share in the discord
   * Working on feature parity on the AS SDK at Fastly
* @jtenner : Working on lunatic and as-bench
   * As-bench: An assembly script benchmarking tool / CLI
      * Similar to as-pect, but for benchmarking. API should be similar and things
* @torch2424 : Runtime chart generator thing
   * I still want to do it if we need it
   * @dcodeIO : I already did it! :)
      * https://github.com/AssemblyScript/assemblyscript/blob/master/lib/rtrace/bin/rtplot.js 
      * `--use ASC_PROFILE=1`
   * We could make this just more generally useful?
   * And example PR: https://github.com/AssemblyScript/assemblyscript/pull/1692

**Comment by torch2424** [comment]
Closing this in favor of: https://github.com/AssemblyScript/working-group/issues/57 

Feel free to continue discussions from this meeting here :smile: :tada:
